# Generated by Django 4.0.2 on 2022-04-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('Vehicle', 'Vehicle'), ('Furniture', 'Furniture'), ('Clothes', 'Clothes'), ('Shoes', 'Shoes'), ('Electronics', 'Electronics'), ('Toys', 'Toys'), ('Kitchen Appliances', 'Kitchen Appliances'), ("Sport's Equipment", "Sport's Equipment"), ('Education', 'Education')], default='Vehicle', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('neighbourhood', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=1000)),
                ('address', models.CharField(default='', max_length=200)),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('pay', models.CharField(default='', max_length=200)),
                ('neighbourhood', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Phone', models.CharField(default='', max_length=8)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('neighbourhood', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=200)),
                ('timeanddate', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=200)),
                ('participantsnumb', models.IntegerField(null=True)),
                ('maxparticipants', models.IntegerField(null=True)),
                ('neighbourhood', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('text', models.TextField(default='', max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('neighbourhood', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.neighbourhood')),
            ],
        ),
    ]
