# Generated by Django 4.0.2 on 2022-04-06 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('Vehicle', 'Vehicle'), ('Furniture', 'Furniture'), ('Clothes', 'Clothes'), ('Shoes', 'Shoes'), ('Electronics', 'Electronics'), ('Toys', 'Toys'), ('Kitchen Appliances', 'Kitchen Appliances'), ("Sport's Equipment", "Sport's Equipment"), ('Education', 'Education')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('pay', models.CharField(max_length=200, null=True)),
                ('neighbourhood', models.ForeignKey(default='Ras Beirut', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(max_length=8, null=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('participantsnumb', models.IntegerField(null=True)),
                ('maxparticipants', models.IntegerField(null=True)),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('text', models.TextField(default='text', max_length=1000, null=True)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.neighbourhood')),
            ],
        ),
    ]
